-- ==========================================
-- 019 — RLS Policies
-- RestauFlow SaaS Multi-Tenant
-- ==========================================

-- Habilitar RLS en TODAS las tablas con tenant_id
ALTER TABLE usuarios                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE locales                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE zonas                         ENABLE ROW LEVEL SECURITY;
ALTER TABLE mesas                         ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracion_restaurante     ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias_menu               ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_horarios                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos_menu                ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_menu_imagenes        ENABLE ROW LEVEL SECURITY;
ALTER TABLE variantes_producto_menu       ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos_modificadores          ENABLE ROW LEVEL SECURITY;
ALTER TABLE modificadores                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_grupos_modificadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE combos                        ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_combos                ENABLE ROW LEVEL SECURITY;
ALTER TABLE promociones                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE cupones                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE insumo_categorias             ENABLE ROW LEVEL SECURITY;
ALTER TABLE unidades_medida               ENABLE ROW LEVEL SECURITY;
ALTER TABLE insumos                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE recetas                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_receta                ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_insumo_por_local        ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_inventario        ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordenes_compra                ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_ordenes_compra        ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE direcciones_cliente           ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_puntos            ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservas                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_estados_reserva     ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordenes                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE items_orden                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE modificadores_item_orden      ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_estados_orden       ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets_cocina                ENABLE ROW LEVEL SECURITY;
ALTER TABLE turnos_caja                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE metodos_pago                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagos                         ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_pagos                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE comprobantes                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE zonas_delivery                ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_ordenes              ENABLE ROW LEVEL SECURITY;
ALTER TABLE seguimiento_delivery          ENABLE ROW LEVEL SECURITY;
ALTER TABLE resumen_diario                ENABLE ROW LEVEL SECURITY;
ALTER TABLE alertas_stock_insumos         ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE tokens_recuperacion           ENABLE ROW LEVEL SECURITY;

-- Políticas de aislamiento por tenant
CREATE POLICY tenant_isolation_usuarios ON usuarios USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_locales ON locales USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_zonas ON zonas USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_mesas ON mesas USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_configuracion ON configuracion_restaurante USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_categorias_menu ON categorias_menu USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_menu_horarios ON menu_horarios USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_productos_menu ON productos_menu USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_producto_imagenes ON producto_menu_imagenes USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_variantes ON variantes_producto_menu USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_grupos_mod ON grupos_modificadores USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_modificadores ON modificadores USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_prod_grupos_mod ON producto_grupos_modificadores USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_combos ON combos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_detalle_combos ON detalle_combos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_promociones ON promociones USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_cupones ON cupones USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_insumo_cat ON insumo_categorias USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_unidades ON unidades_medida USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_insumos ON insumos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_recetas ON recetas USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_detalle_receta ON detalle_receta USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_stock_local ON stock_insumo_por_local USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_mov_inv ON movimientos_inventario USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_proveedores ON proveedores USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_ordenes_compra ON ordenes_compra USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_det_oc ON detalle_ordenes_compra USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_clientes ON clientes USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_dir_cliente ON direcciones_cliente USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_mov_puntos ON movimientos_puntos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_reservas ON reservas USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_hist_reserva ON historial_estados_reserva USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_ordenes ON ordenes USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_items_orden ON items_orden USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_mod_item ON modificadores_item_orden USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_hist_orden ON historial_estados_orden USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_tickets ON tickets_cocina USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_turnos ON turnos_caja USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_met_pago ON metodos_pago USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_pagos ON pagos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_det_pagos ON detalle_pagos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_comprobantes ON comprobantes USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_zonas_del ON zonas_delivery USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_del_ordenes ON delivery_ordenes USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_seg_del ON seguimiento_delivery USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_resumen ON resumen_diario USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_alertas ON alertas_stock_insumos USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_audit ON audit_log USING (tenant_id = current_setting('app.tenant_id')::uuid);
CREATE POLICY tenant_isolation_tokens ON tokens_recuperacion USING (tenant_id = current_setting('app.tenant_id')::uuid);
